### ISSUE TITLE
Mini-DP working for you?

### ISSUE THREAD

**Issue by josefnorlin** [thebinh-lg051/ThinkPad-T440s-Hackintosh#2]
Hey,

I'm grateful for your config files here. I try to get my X240 working with uses the same processor and graphics card as your T440s. However, I have an issue with getting the Mini-DP port working. I works plugin in but can't give the external display 1080p (1080 interlaced seem to work).

How is that working for you?

**Comment by banhbaoxamlan** [comment]
Yes, it works, I add the con1 and con2 framebuffer patches to config.plist

```
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-alldata</key>
				<data>AQUSAAAEAACHAAAA</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-alldata</key>
				<data>AgQSABAAAACHAAAA</data>
```

**Comment by lbngoc** [comment]
Hi @banhbaoxamlan, I know this issuse was closed but I wonder if Mini DP is also working on T440? As tested, I could only connect with external monitor use Mini DP -> VGA cable. If connect via Mini DP -> HDMI cable, my screen was changed into grey and stucked.

**Comment by thebinh-lg051** [comment]
> Hi @banhbaoxamlan, I know this issuse was closed but I wonder if Mini DP is also working on T440? As tested, I could only connect with external monitor use Mini DP -> VGA cable. If connect via Mini DP -> HDMI cable, my screen was changed into grey and stucked.

bạn thử thêm :
```
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
```

**Comment by lbngoc** [comment]
> > Hi @banhbaoxamlan, I know this issuse was closed but I wonder if Mini DP is also working on T440? As tested, I could only connect with external monitor use Mini DP -> VGA cable. If connect via Mini DP -> HDMI cable, my screen was changed into grey and stucked.
> 
> bạn thử thêm :
> 
> ```
> 				<key>enable-hdmi20</key>
> 				<data>AQAAAA==</data>
> ```

It's working !
Cám ơn bạn rất nhiều 🤩
