### ISSUE TITLE
安装10.15.3后，电池状态不显示

### ISSUE THREAD

**Issue by fsnhljz** [thebinh-lg051/ThinkPad-T440s-Hackintosh#3]
求大佬修复或者告知怎么解决，另外蓝牙不能用。偶尔合盖后休眠不能唤醒

**Comment by ryan201702** [comment]
FYI : https://github.com/304790738/ThinkPad-T440s-Hackintosh

**Comment by fsnhljz** [comment]
> FYI : https://github.com/304790738/ThinkPad-T440s-Hackintosh

how to get USBPorts.kext？

**Comment by ryan201702** [comment]
> > FYI : https://github.com/304790738/ThinkPad-T440s-Hackintosh
> 
> how to get USBPorts.kext？

please see branch 10.15.2:
https://github.com/304790738/ThinkPad-T440s-Hackintosh/tree/10.15.2

`Hackintosh MacOS , the branch number is the version of MacOS,

e.g :

branch ---> MacOS version

10.15.2 ---> 10.15.2`
