### ISSUE TITLE
耳机口有杂音

### ISSUE THREAD

**Issue by fsnhljz** [thebinh-lg051/ThinkPad-T440s-Hackintosh#5]
请问耳机口有杂音这个怎么能够解决？
另外更换网卡的话，是否需要再弄白名单，还是说刷了BIOS to v2.36 version就已经相当于刷了白名单，不需要再做其他了？

**Comment by banhbaoxamlan** [comment]
I have updated README for this issues, u can try this to fix headphone

Good luck <3

**Comment by banhbaoxamlan** [comment]
If you want to use WIFI, Intel WIFI not support, you need to downgrade BIOS to v2.36 or mod BIOS to remove WiFi Whitelist

**Comment by fsnhljz** [comment]
WiFi，是不是购买1820a替换就可以了？BIOS已经是2.36了，还需要做一些什么设置吗？

**Comment by fsnhljz** [comment]
> I have updated README for this issues, u can try this to fix headphone
> 
> Good luck <3

can not work
`cp: /usr/bin/ALCPlugFix: Read-only file system
chmod: /usr/bin/ALCPlugFix: No such file or directory
chown: /usr/bin/ALCPlugFix: No such file or directory
cp: /usr/bin/hda-verb: Read-only file system
chmod: /usr/bin/hda-verb: No such file or directory
chown: /usr/bin/hda-verb: No such file or directory
/Library/LaunchDaemons/good.win.ALCPlugFix.plist: service already loaded
Done!
`

**Comment by banhbaoxamlan** [comment]
Apple has changed the System partition of macOS Catalina to be read-only by default.
Open terminal and paste the following commands:
```
sudo mount -uw /
sudo killall Finder
```

After this, run again alc fix

**Comment by banhbaoxamlan** [comment]
> WiFi，是不是购买1820a替换就可以了？BIOS已经是2.36了，还需要做一些什么设置吗？

it's ok, now you can replace DW1820A
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html

**Comment by fsnhljz** [comment]
> > WiFi，是不是购买1820a替换就可以了？BIOS已经是2.36了，还需要做一些什么设置吗？
> 
> it's ok, now you can replace DW1820A
> https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html

i ues tp-link tl-wn823n v3 is word good, bug just 2.4g wifi

**Comment by banhbaoxamlan** [comment]
> > > WiFi，是不是购买1820a替换就可以了？BIOS已经是2.36了，还需要做一些什么设置吗？
> > 
> > 
> > it's ok, now you can replace DW1820A
> > https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
> 
> i ues tp-link tl-wn823n v3 is word good, bug just 2.4g wifi

usb wifi, i recommend cf-811ac, it support dual band 2.4 and 5.0 GHz

**Comment by 304790738** [comment]
> > I have updated README for this issues, u can try this to fix headphone
> > Good luck <3
> 
> can not work
> `
> cp: /usr/bin/ALCPlugFix: Read-only file system
> 
> chmod: /usr/bin/ALCPlugFix: No such file or directory
> chown: /usr/bin/ALCPlugFix: No such file or directory
> cp: /usr/bin/hda-verb: Read-only file system
> chmod: /usr/bin/hda-verb: No such file or directory
> chown: /usr/bin/hda-verb: No such file or directory
> /Library/LaunchDaemons/good.win.ALCPlugFix.plist: service already loaded
> Done!
> `



> 请问耳机口有杂音这个怎么能够解决？
> 另外更换网卡的话，是否需要再弄白名单，还是说刷了BIOS to v2.36 version就已经相当于刷了白名单，不需要再做其他了？

解决了吗，我的是直接插耳机启动机器就可以正常用，不插耳机启动机器，然后再插上耳机就会出现白噪声。
