### ISSUE TITLE
usb一个口不工作

### ISSUE THREAD

**Issue by smg-cyber** [thebinh-lg051/ThinkPad-T440s-Hackintosh#6]
有一个usb口失效，无法检测与工作

**Comment by banhbaoxamlan** [comment]
> 有一个usb口失效，无法检测与工作
I used HS01 + SS01 for left usb port, HS02 + SS02 for right usb port, HS06 for fingerprint reader but I have disabled in BIOS, dont need it. HS07 for Bluetooth and HS08 camera

**Comment by thebinh-lg051** [comment]
> 有一个usb口失效，无法检测与工作

I edited my SSDT-UAIC, add HS03 + SS03 for usb port missing, thanks for report <3
