### ISSUE TITLE
dw1560 bluetooth, how to get it work?

### ISSUE THREAD

**Issue by webnah** [thebinh-lg051/ThinkPad-T440s-Hackintosh#7]
wifi I worked
but bluetooth not 
1. copy all 4 files to Others/
![image](https://user-images.githubusercontent.com/46319124/77240796-b59beb80-6c1c-11ea-928d-8a7b6ed8fac4.png)
2. reboot, wifi ok
but blue tooth not found 

![image](https://user-images.githubusercontent.com/46319124/77240808-d06e6000-6c1c-11ea-9a5f-d484123c2d90.png)

![image](https://user-images.githubusercontent.com/46319124/77240816-e11ed600-6c1c-11ea-9762-b7ee1b992639.png)

thank you for your greet EFI, my laptop t440s. i7 8g, dw1560 wifi + bluetooth

**Comment by banhbaoxamlan** [comment]
Hi <3, thanks for use my EFI
Download SSDT-UIAC.dsl on my github, use iasl dsl > aml, copy it to ACPI/patched/
Delete USBPorts.kext on kexts/Other/, download USBInjectAll.kext, recaches and reboot

**Comment by webnah** [comment]
it worked
