### ISSUE TITLE
内存显示不正确是否有解决办法？

### ISSUE THREAD

**Issue by smg-cyber** [thebinh-lg051/ThinkPad-T440s-Hackintosh#8]
你的配置也是12GB我的也是，但是却显示16GB,使用你的efi一切都还正常，只是开机速度比较慢，https://github.com/jsassu20/Lenovo-ThinkPad-T440s-Catalina这个和你这个对比了一下，是否可以综合优化一下？

**Comment by banhbaoxamlan** [comment]
您无需担心RAM显示，这是正常的。 目前最好的方法是使用OpenCore，它速度很快，但仍在开发中，因此我没有使用过，请尝试一下
(google translate)

**Comment by smg-cyber** [comment]
OK

**Comment by thebinh-lg051** [comment]
我正在尝试做OpenCore，我已经上传了Config，可以根据需要尝试
(google translate)

**Comment by smg-cyber** [comment]
Thank you for your efforts, I will continue to pay attention and test!
